#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grup3_OOP.DB
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="kutuphane")]
	public partial class KutuphaneDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertkitap(kitap instance);
    partial void Updatekitap(kitap instance);
    partial void Deletekitap(kitap instance);
    partial void Insertogrenci(ogrenci instance);
    partial void Updateogrenci(ogrenci instance);
    partial void Deleteogrenci(ogrenci instance);
    partial void Inserttur(tur instance);
    partial void Updatetur(tur instance);
    partial void Deletetur(tur instance);
    partial void Insertyazar(yazar instance);
    partial void Updateyazar(yazar instance);
    partial void Deleteyazar(yazar instance);
    #endregion
		
		public KutuphaneDataContext() : 
				base(global::Grup3_OOP.Properties.Settings.Default.kutuphaneConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KutuphaneDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KutuphaneDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KutuphaneDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KutuphaneDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<islem> islems
		{
			get
			{
				return this.GetTable<islem>();
			}
		}
		
		public System.Data.Linq.Table<kitap> kitaps
		{
			get
			{
				return this.GetTable<kitap>();
			}
		}
		
		public System.Data.Linq.Table<ogrenci> ogrencis
		{
			get
			{
				return this.GetTable<ogrenci>();
			}
		}
		
		public System.Data.Linq.Table<tur> turs
		{
			get
			{
				return this.GetTable<tur>();
			}
		}
		
		public System.Data.Linq.Table<yazar> yazars
		{
			get
			{
				return this.GetTable<yazar>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.islem")]
	public partial class islem
	{
		
		private int _islemno;
		
		private System.Nullable<int> _ogrno;
		
		private System.Nullable<int> _kitapno;
		
		private System.Nullable<System.DateTime> _atarih;
		
		private System.Nullable<System.DateTime> _vtarih;
		
		public islem()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_islemno", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int islemno
		{
			get
			{
				return this._islemno;
			}
			set
			{
				if ((this._islemno != value))
				{
					this._islemno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ogrno", DbType="Int")]
		public System.Nullable<int> ogrno
		{
			get
			{
				return this._ogrno;
			}
			set
			{
				if ((this._ogrno != value))
				{
					this._ogrno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kitapno", DbType="Int")]
		public System.Nullable<int> kitapno
		{
			get
			{
				return this._kitapno;
			}
			set
			{
				if ((this._kitapno != value))
				{
					this._kitapno = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_atarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> atarih
		{
			get
			{
				return this._atarih;
			}
			set
			{
				if ((this._atarih != value))
				{
					this._atarih = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vtarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> vtarih
		{
			get
			{
				return this._vtarih;
			}
			set
			{
				if ((this._vtarih != value))
				{
					this._vtarih = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.kitap")]
	public partial class kitap : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kitapno;
		
		private string _isbnno;
		
		private string _kitapadi;
		
		private System.Nullable<int> _yazarno;
		
		private System.Nullable<int> _turno;
		
		private System.Nullable<int> _sayfasayisi;
		
		private System.Nullable<int> _puan;
		
		private EntityRef<tur> _tur;
		
		private EntityRef<yazar> _yazar;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkitapnoChanging(int value);
    partial void OnkitapnoChanged();
    partial void OnisbnnoChanging(string value);
    partial void OnisbnnoChanged();
    partial void OnkitapadiChanging(string value);
    partial void OnkitapadiChanged();
    partial void OnyazarnoChanging(System.Nullable<int> value);
    partial void OnyazarnoChanged();
    partial void OnturnoChanging(System.Nullable<int> value);
    partial void OnturnoChanged();
    partial void OnsayfasayisiChanging(System.Nullable<int> value);
    partial void OnsayfasayisiChanged();
    partial void OnpuanChanging(System.Nullable<int> value);
    partial void OnpuanChanged();
    #endregion
		
		public kitap()
		{
			this._tur = default(EntityRef<tur>);
			this._yazar = default(EntityRef<yazar>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kitapno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kitapno
		{
			get
			{
				return this._kitapno;
			}
			set
			{
				if ((this._kitapno != value))
				{
					this.OnkitapnoChanging(value);
					this.SendPropertyChanging();
					this._kitapno = value;
					this.SendPropertyChanged("kitapno");
					this.OnkitapnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_isbnno", DbType="Char(20)")]
		public string isbnno
		{
			get
			{
				return this._isbnno;
			}
			set
			{
				if ((this._isbnno != value))
				{
					this.OnisbnnoChanging(value);
					this.SendPropertyChanging();
					this._isbnno = value;
					this.SendPropertyChanged("isbnno");
					this.OnisbnnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kitapadi", DbType="VarChar(100)")]
		public string kitapadi
		{
			get
			{
				return this._kitapadi;
			}
			set
			{
				if ((this._kitapadi != value))
				{
					this.OnkitapadiChanging(value);
					this.SendPropertyChanging();
					this._kitapadi = value;
					this.SendPropertyChanged("kitapadi");
					this.OnkitapadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yazarno", DbType="Int")]
		public System.Nullable<int> yazarno
		{
			get
			{
				return this._yazarno;
			}
			set
			{
				if ((this._yazarno != value))
				{
					if (this._yazar.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnyazarnoChanging(value);
					this.SendPropertyChanging();
					this._yazarno = value;
					this.SendPropertyChanged("yazarno");
					this.OnyazarnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno", DbType="Int")]
		public System.Nullable<int> turno
		{
			get
			{
				return this._turno;
			}
			set
			{
				if ((this._turno != value))
				{
					if (this._tur.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnturnoChanging(value);
					this.SendPropertyChanging();
					this._turno = value;
					this.SendPropertyChanged("turno");
					this.OnturnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sayfasayisi", DbType="Int")]
		public System.Nullable<int> sayfasayisi
		{
			get
			{
				return this._sayfasayisi;
			}
			set
			{
				if ((this._sayfasayisi != value))
				{
					this.OnsayfasayisiChanging(value);
					this.SendPropertyChanging();
					this._sayfasayisi = value;
					this.SendPropertyChanged("sayfasayisi");
					this.OnsayfasayisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puan", DbType="Int")]
		public System.Nullable<int> puan
		{
			get
			{
				return this._puan;
			}
			set
			{
				if ((this._puan != value))
				{
					this.OnpuanChanging(value);
					this.SendPropertyChanging();
					this._puan = value;
					this.SendPropertyChanged("puan");
					this.OnpuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tur_kitap", Storage="_tur", ThisKey="turno", OtherKey="turno", IsForeignKey=true, DeleteRule="CASCADE")]
		public tur tur
		{
			get
			{
				return this._tur.Entity;
			}
			set
			{
				tur previousValue = this._tur.Entity;
				if (((previousValue != value) 
							|| (this._tur.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tur.Entity = null;
						previousValue.kitaps.Remove(this);
					}
					this._tur.Entity = value;
					if ((value != null))
					{
						value.kitaps.Add(this);
						this._turno = value.turno;
					}
					else
					{
						this._turno = default(Nullable<int>);
					}
					this.SendPropertyChanged("tur");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yazar_kitap", Storage="_yazar", ThisKey="yazarno", OtherKey="yazarno", IsForeignKey=true, DeleteRule="CASCADE")]
		public yazar yazar
		{
			get
			{
				return this._yazar.Entity;
			}
			set
			{
				yazar previousValue = this._yazar.Entity;
				if (((previousValue != value) 
							|| (this._yazar.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._yazar.Entity = null;
						previousValue.kitaps.Remove(this);
					}
					this._yazar.Entity = value;
					if ((value != null))
					{
						value.kitaps.Add(this);
						this._yazarno = value.yazarno;
					}
					else
					{
						this._yazarno = default(Nullable<int>);
					}
					this.SendPropertyChanged("yazar");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ogrenci")]
	public partial class ogrenci : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ogrno;
		
		private string _ograd;
		
		private string _ogrsoyad;
		
		private System.Nullable<char> _cinsiyet;
		
		private System.Nullable<System.DateTime> _dtarih;
		
		private string _sinif;
		
		private System.Nullable<long> _puan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnogrnoChanging(int value);
    partial void OnogrnoChanged();
    partial void OnogradChanging(string value);
    partial void OnogradChanged();
    partial void OnogrsoyadChanging(string value);
    partial void OnogrsoyadChanged();
    partial void OncinsiyetChanging(System.Nullable<char> value);
    partial void OncinsiyetChanged();
    partial void OndtarihChanging(System.Nullable<System.DateTime> value);
    partial void OndtarihChanged();
    partial void OnsinifChanging(string value);
    partial void OnsinifChanged();
    partial void OnpuanChanging(System.Nullable<long> value);
    partial void OnpuanChanged();
    #endregion
		
		public ogrenci()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ogrno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ogrno
		{
			get
			{
				return this._ogrno;
			}
			set
			{
				if ((this._ogrno != value))
				{
					this.OnogrnoChanging(value);
					this.SendPropertyChanging();
					this._ogrno = value;
					this.SendPropertyChanged("ogrno");
					this.OnogrnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ograd", DbType="NChar(10)")]
		public string ograd
		{
			get
			{
				return this._ograd;
			}
			set
			{
				if ((this._ograd != value))
				{
					this.OnogradChanging(value);
					this.SendPropertyChanging();
					this._ograd = value;
					this.SendPropertyChanged("ograd");
					this.OnogradChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ogrsoyad", DbType="NChar(20)")]
		public string ogrsoyad
		{
			get
			{
				return this._ogrsoyad;
			}
			set
			{
				if ((this._ogrsoyad != value))
				{
					this.OnogrsoyadChanging(value);
					this.SendPropertyChanging();
					this._ogrsoyad = value;
					this.SendPropertyChanged("ogrsoyad");
					this.OnogrsoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cinsiyet", DbType="NChar(1)")]
		public System.Nullable<char> cinsiyet
		{
			get
			{
				return this._cinsiyet;
			}
			set
			{
				if ((this._cinsiyet != value))
				{
					this.OncinsiyetChanging(value);
					this.SendPropertyChanging();
					this._cinsiyet = value;
					this.SendPropertyChanged("cinsiyet");
					this.OncinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dtarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> dtarih
		{
			get
			{
				return this._dtarih;
			}
			set
			{
				if ((this._dtarih != value))
				{
					this.OndtarihChanging(value);
					this.SendPropertyChanging();
					this._dtarih = value;
					this.SendPropertyChanged("dtarih");
					this.OndtarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sinif", DbType="NChar(4)")]
		public string sinif
		{
			get
			{
				return this._sinif;
			}
			set
			{
				if ((this._sinif != value))
				{
					this.OnsinifChanging(value);
					this.SendPropertyChanging();
					this._sinif = value;
					this.SendPropertyChanged("sinif");
					this.OnsinifChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puan", DbType="BigInt")]
		public System.Nullable<long> puan
		{
			get
			{
				return this._puan;
			}
			set
			{
				if ((this._puan != value))
				{
					this.OnpuanChanging(value);
					this.SendPropertyChanging();
					this._puan = value;
					this.SendPropertyChanged("puan");
					this.OnpuanChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tur")]
	public partial class tur : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _turno;
		
		private string _turadi;
		
		private EntitySet<kitap> _kitaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnturnoChanging(int value);
    partial void OnturnoChanged();
    partial void OnturadiChanging(string value);
    partial void OnturadiChanged();
    #endregion
		
		public tur()
		{
			this._kitaps = new EntitySet<kitap>(new Action<kitap>(this.attach_kitaps), new Action<kitap>(this.detach_kitaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int turno
		{
			get
			{
				return this._turno;
			}
			set
			{
				if ((this._turno != value))
				{
					this.OnturnoChanging(value);
					this.SendPropertyChanging();
					this._turno = value;
					this.SendPropertyChanged("turno");
					this.OnturnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_turadi", DbType="NChar(30)")]
		public string turadi
		{
			get
			{
				return this._turadi;
			}
			set
			{
				if ((this._turadi != value))
				{
					this.OnturadiChanging(value);
					this.SendPropertyChanging();
					this._turadi = value;
					this.SendPropertyChanged("turadi");
					this.OnturadiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tur_kitap", Storage="_kitaps", ThisKey="turno", OtherKey="turno")]
		public EntitySet<kitap> kitaps
		{
			get
			{
				return this._kitaps;
			}
			set
			{
				this._kitaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_kitaps(kitap entity)
		{
			this.SendPropertyChanging();
			entity.tur = this;
		}
		
		private void detach_kitaps(kitap entity)
		{
			this.SendPropertyChanging();
			entity.tur = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.yazar")]
	public partial class yazar : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _yazarno;
		
		private string _yazarad;
		
		private string _yazarsoyad;
		
		private EntitySet<kitap> _kitaps;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnyazarnoChanging(int value);
    partial void OnyazarnoChanged();
    partial void OnyazaradChanging(string value);
    partial void OnyazaradChanged();
    partial void OnyazarsoyadChanging(string value);
    partial void OnyazarsoyadChanged();
    #endregion
		
		public yazar()
		{
			this._kitaps = new EntitySet<kitap>(new Action<kitap>(this.attach_kitaps), new Action<kitap>(this.detach_kitaps));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yazarno", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int yazarno
		{
			get
			{
				return this._yazarno;
			}
			set
			{
				if ((this._yazarno != value))
				{
					this.OnyazarnoChanging(value);
					this.SendPropertyChanging();
					this._yazarno = value;
					this.SendPropertyChanged("yazarno");
					this.OnyazarnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yazarad", DbType="NChar(20)")]
		public string yazarad
		{
			get
			{
				return this._yazarad;
			}
			set
			{
				if ((this._yazarad != value))
				{
					this.OnyazaradChanging(value);
					this.SendPropertyChanging();
					this._yazarad = value;
					this.SendPropertyChanged("yazarad");
					this.OnyazaradChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_yazarsoyad", DbType="NChar(20)")]
		public string yazarsoyad
		{
			get
			{
				return this._yazarsoyad;
			}
			set
			{
				if ((this._yazarsoyad != value))
				{
					this.OnyazarsoyadChanging(value);
					this.SendPropertyChanging();
					this._yazarsoyad = value;
					this.SendPropertyChanged("yazarsoyad");
					this.OnyazarsoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="yazar_kitap", Storage="_kitaps", ThisKey="yazarno", OtherKey="yazarno")]
		public EntitySet<kitap> kitaps
		{
			get
			{
				return this._kitaps;
			}
			set
			{
				this._kitaps.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_kitaps(kitap entity)
		{
			this.SendPropertyChanging();
			entity.yazar = this;
		}
		
		private void detach_kitaps(kitap entity)
		{
			this.SendPropertyChanging();
			entity.yazar = null;
		}
	}
}
#pragma warning restore 1591
